rover:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  four_wheel_steering_controller:
    type        : "four_wheel_steering_controller/FourWheelSteeringController"
    front_wheel: ['ffr_wheel_joint', 'ffl_wheel_joint']
    rear_wheel: ['rfr_wheel_joint', 'rfl_wheel_joint']
    front_steering: ['front_right_steering_joint', 'front_left_steering_joint']
    rear_steering: ['rear_right_steering_joint', 'rear_left_steering_joint']

    publish_rate: 50.0
    pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    cmd_vel_timeout: 25.0 # not tested here

    # Wheel separation and diameter. These are both optional.
    # diff_drive_controller will attempt to read either one or both from the
    # URDF if not specified as a parameter
    # wheel_separation : 0.122
    wheel_separation_h : 0.2
    wheel_separation_w : 0.2
    wheel_radius : 0.25
    wheel_steering_y_offset : -0.1
    # wheel_steering_x_offset : 0.03

    # Wheel separation and radius multipliers
    wheel_separation_multiplier: 1.0
    wheel_radius_multiplier    : 1.0

    # Velocity commands timeout [s], default 0.5
    cmd_vel_timeout: 1.0
    
    # Base frame_id
    # base_frame_id: base_footprint #default: base_link
    base_frame_id: base_link

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 50  # m/s
        min_velocity           : -50 # m/s
        has_acceleration_limits: true
        max_acceleration       : 50.0  # m/s^2
        min_acceleration       : -50.0 # m/s^2
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 1.57  # rad/s
        min_velocity           : -1.57
        has_acceleration_limits: true
        max_acceleration       : 4.0  # rad/s^2
        min_acceleration       : -4.0

    /rover/gazebo_ros_control:
      pid_gains:
        front_left_steering_joint:
          p: 100
          i: 1
          d: 0.01
        front_right_steering_joint:
          p: 100
          i: 1
          d: 0.01
        rear_left_steering_joint:
          p: 100
          i: 1
          d: 0.01
        rear_right_steering_joint:
          p: 100
          i: 1
          d: 0.01
        ffl_wheel_joint: #front_left_wheel
          p: 10.0
          i: 1
          d: 0.0
        ffr_wheel_joint: #front_right_wheel
          p: 10.0
          i: 1
          d: 0.0
        rfl_wheel_joint: #rear_left_wheel
          p: 10.0
          i: 1
          d: 0.0
        rfr_wheel_joint: #rear_right_wheel
          p: 10.0
          i: 1
          d: 0.0
          
        # fl_wheel: #front_left_wheel
        #   p: 10.0
        #   i: 1
        #   d: 0.0
        # fr_wheel: #front_right_wheel
        #   p: 10.0
        #   i: 1
        #   d: 0.0
        # rl_wheel: #rear_left_wheel
        #   p: 10.0
        #   i: 1
        #   d: 0.0
        # rr_wheel: #rear_right_wheel
        #   p: 10.0
        #   i: 1
        #   d: 0.0
  rover_suspension_ffl_controller:
    type: velocity_controllers/JointVelocityController
    joint: ffl_suspension_joint
    pid:
      p: 100.0
      i: 1.0
      d: 0.0
      i_clamp: 100.0

  rover_suspension_ffr_controller:
    type: velocity_controllers/JointVelocityController
    joint: ffr_suspension_joint
    pid:
      p: 100.0
      i: 1.0
      d: 0.0
      i_clamp: 100.0

  rover_suspension_rfl_controller:
    type: velocity_controllers/JointVelocityController
    joint: rfl_suspension_joint
    pid:
      p: 100.0
      i: 1.0
      d: 0.0
      i_clamp: 100.0

  rover_suspension_rfr_controller:
    type: velocity_controllers/JointVelocityController
    joint: rfr_suspension_joint
    pid:
      p: 100.0
      i: 1.0
      d: 0.0
      i_clamp: 100.0




  # suspension_velocity_controller:
  #   type: "diff_drive_controller/DiffDriveController"
  #   left_wheel: ['ffl_suspension_joint', 'rfl_suspension_joint']
  #   right_wheel: ['ffr_suspension_joint', 'rfr_suspension_joint']
  #   publish_rate: 50
  #   pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  #   twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  #   cmd_vel_timeout: 0.25
  #   wheel_radius : 0.25
  #   velocity_rolling_window_size: 0.1

  #   # Base frame_id
  #   base_frame_id: base_link

  # # Odometry fused with IMU is published by robot_localization, so
  #   # no need to publish a TF based on encoders alone.
  #   enable_odom_tf: false

  #   # Husky hardware provides wheel velocities
  #   estimate_velocity_from_position: false

  #   # Wheel separation and radius multipliers
  #   wheel_separation_multiplier:  1.0 # default: 1.0
  #   wheel_radius_multiplier    : 1.0  # default: 1.0

  #   # Velocity and acceleration limits
  #   # Whenever a min_* is unspecified, default to -max_*
  #   linear:
  #     x:
  #       has_velocity_limits    : true
  #       max_velocity           : 2.0   # m/s
  #       has_acceleration_limits: true
  #       max_acceleration       : 3.0   # m/s^2
  #   angular:
  #     z:
  #       has_velocity_limits    : true
  #       max_velocity           : 2.0   # rad/s
  #       has_acceleration_limits: true
  #       max_acceleration       : 6.0   # rad/s^2
  #   /rover/gazebo_ros_control:
  #         pid_gains:
  #           ffl_suspension_joint:
  #             p: 10.0
  #             i: 1.0
  #             d: 0.0
  #           ffr_suspension_joint:
  #             p: 10.0
  #             i: 1.0
  #             d: 0.0
  #           rfl_suspension_joint:
  #             p: 10.0
  #             i: 1.0
  #             d: 0.0
  #           rfr_suspension_joint:
  #             p: 10.0
  #             i: 1.0
  #             d: 0.0